---
version: "3"

services:
  core:
    build:
      dockerfile: ./docker/Dockerfile.development
      context: .
    restart: always
    command: yarn start:dev
    ports:
      - 3000:3000
    environment:
      - DEBUG=${DEBUG:-true}
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mocks
      - POSTGRES_USER=mimo
      - POSTGRES_PASSWORD=asd123
